[package]
name = "input"
version = "0.1.0"
authors = ["rust-lang-ja Developers"]
edition = "2018"
description = "Provides an `input!` macro for the `examples`."
license = "CC0-1.0"
publish = false

[dependencies]
